version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-flyway
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: finance
    ports:
      - "8080:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build: .
    container_name: finance-api
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/finance
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8090:8090"
    networks:
      - backend


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      - api
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - backend
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  postgres_data:

networks:
  backend: