CREATE TABLE IF NOT EXISTS PROFILE(
    ID UUID PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CODE BIGINT UNIQUE NOT NULL,
    ROLE VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "USER" (
    ID UUID PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    PROFILE UUID
);

ALTER TABLE "USER"
    ADD CONSTRAINT fk_user_profile
    FOREIGN KEY (PROFILE)
    REFERENCES PROFILE;

CREATE TABLE IF NOT EXISTS CATEGORY(
    ID UUID PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS TRANSACTION(
    ID UUID PRIMARY KEY,
    AMOUNT DOUBLE PRECISION,
    DATE DATE,
    TYPE VARCHAR(50),
    CATEGORY UUID,
    "USER" UUID
);